#!/bin/sh

uci -q set network.lan.ipaddr='192.168.6.1'
uci -q commit network

uci -q set luci.main.lang='zh_cn'
uci -q set luci.main.mediaurlbase='/luci-static/argon'
uci -q commit luci

uci -q set firewall.@defaults[0].flow_offloading='1'
uci -q set firewall.@defaults[0].flow_offloading_hw='1'
uci -q commit firewall

[ -x /etc/init.d/mtkhnat ] && /etc/init.d/mtkhnat enable
[ -x /etc/init.d/smp ] && /etc/init.d/smp enable

exit 0
